name: 버그 리포트 (웹 인터페이스)
description: Mastodon의 웹 인터페이스 사용 중 문제가 있습니다.
labels: [bug, 'status/to triage', 'area/web interface']
body:
  - type: markdown
    attributes:
      value: |
        이전에 보고되지 않았거나 이미 수정되지 않은 새로운 버그를 제출하고 있는지 확인하세요.

        이슈 제목은 간결하고 명확하게 작성해 주세요.
  - type: textarea
    attributes:
      label: 문제 재현 단계
      description: 무엇을 하려고 했나요?
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: input
    attributes:
      label: 예상 동작
      description: 어떻게 동작해야 했나요?
    validations:
      required: true
  - type: input
    attributes:
      label: 실제 동작
      description: 무슨 일이 일어났나요?
    validations:
      required: true
  - type: textarea
    attributes:
      label: 상세 설명
    validations:
      required: false
  - type: input
    attributes:
      label: Mastodon 인스턴스
      description: 문제가 발생한 Mastodon 인스턴스의 주소
      placeholder: sharlayan.in
    validations:
      required: true
  - type: input
    attributes:
      label: Mastodon 버전
      description: |
        정보(About) 페이지 하단에 표시됩니다. 예: `v4.5.0-beta.1`
      placeholder: v4.5.0-beta.1
    validations:
      required: true
  - type: input
    attributes:
      label: 브라우저 이름 및 버전
      description: |
        이 버그가 발생한 브라우저는 무엇인가요? 버전도 함께 명시해 주세요.
      placeholder: Firefox 139.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: 운영체제
      description: |
        어떤 OS를 사용하고 있나요? 버전도 함께 명시해 주세요.
      placeholder: macOS 15.5
    validations:
      required: true
  - type: textarea
    attributes:
      label: 기술적 세부사항
      description: |
        추가적인 기술적 세부사항이 있다면 작성해 주세요. 전체 오류 로그, 인스펙터 출력 등을 포함할 수 있습니다.
    validations:
      required: false
