name: 배포 문제 해결
description: |
  서버 관리자로서 Mastodon 설치, 업그레이드 또는 운영 중 기술적 문제가 발생했습니다.
labels: [bug, 'status/to triage']
body:
  - type: markdown
    attributes:
      value: |
        이전에 보고되지 않았거나 이미 수정되지 않은 새로운 버그를 제출하고 있는지 확인하세요.

        이슈 제목은 간결하고 명확하게 작성해 주세요.
  - type: textarea
    attributes:
      label: 문제 재현 단계
      description: 무엇을 하려고 했나요?
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: input
    attributes:
      label: 예상 동작
      description: 어떻게 동작해야 했나요?
    validations:
      required: true
  - type: input
    attributes:
      label: 실제 동작
      description: 무슨 일이 일어났나요?
    validations:
      required: true
  - type: textarea
    attributes:
      label: 상세 설명
    validations:
      required: false
  - type: input
    attributes:
      label: Mastodon 인스턴스
      description: 문제가 발생한 Mastodon 인스턴스의 주소
      placeholder: sharlayan.in
    validations:
      required: true
  - type: input
    attributes:
      label: Mastodon 버전
      description: |
        정보(About) 페이지 하단에 표시됩니다. 예: `v4.4.0-alpha.1`
      placeholder: v4.4.0-beta.1
    validations:
      required: false
  - type: textarea
    attributes:
      label: 환경
      description: |
        Mastodon 배포 방식, 컨테이너 사용 여부, 버전 번호 등 환경에 대한 세부정보
      value: |
        최소한 다음 정보를 포함해 주세요:
        - 운영체제: (예: Ubuntu 24.04.2)
        - Ruby 버전: (`ruby --version`에서 확인, 예: v4.0.6)
        - Node.js 버전: (`node --version`에서 확인, 예: v22.16.0)
    validations:
      required: false
  - type: textarea
    attributes:
      label: 기술적 세부사항
      description: |
        로그나 오류 추적과 같은 추가적인 기술적 세부사항
    validations:
      required: false
