name: 기능 요청
description: 제안 사항이 있습니다
labels: [suggestion]
body:
  - type: markdown
    attributes:
      value: |
        이슈 제목은 간결하고 명확하게 작성해 주세요.

        고려 사항: REST API를 사용하는 서드파티 앱으로 구현할 수 있을까요?
  - type: textarea
    attributes:
      label: 제안 내용
      description: 기능에 대한 아이디어를 설명해 주세요. 이전에 제안/구현/거부되지 않았는지 확인하세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 동기
      description: 이 기능이 왜 필요하다고 생각하나요? 누가 혜택을 받을까요?
    validations:
      required: true
