# This file contains default values, and does not need to be edited. All
# important settings can be changed from the admin interface.

defaults: &defaults
  site_title: 'Mastodon Macaron Edition'
  site_short_description: ''
  theme_color: '#007046'
  site_description: ''
  site_extended_description: ''
  site_terms: ''
  site_contact_username: ''
  site_contact_email: ''
  registrations_mode: 'none'
  profile_directory: true
  closed_registrations_message: ''
  force_local_only: false
  local_account_statuses_access: 'public'
  local_status_page_access: 'public'
  local_live_feed_access: 'authenticated'
  remote_live_feed_access: 'authenticated'
  local_topic_feed_access: 'authenticated'
  remote_topic_feed_access: 'authenticated'
  show_staff_badge: true
  preview_sensitive_media: false
  noindex: false
  flavour: 'glitch'
  skin: 'default'
  thumbnail_description: ''
  trends: true
  trendable_by_default: false
  trending_status_cw: true
  visible_reactions: 6
  hide_followers_count: false
  disallowed_hashtags: # space separated string or list of hashtags without the hash
  bootstrap_timeline_accounts: ''
  activity_api_enabled: true
  peers_api_enabled: true
  show_reblogs_in_public_timelines: false
  show_replies_in_public_timelines: false
  default_content_type: 'text/plain'
  show_domain_blocks: 'disabled'
  show_domain_blocks_rationale: 'disabled'
  outgoing_spoilers: ''
  require_invite_text: false
  backups_retention_period: 7
  captcha_enabled: false
  allow_referrer_origin: false
  show_instance_info: true
  instance_metadata_enabled: true
  custom_emoji_size: false
  reaction_custom_emoji_size: false
  reaction_local_emoji_only: true
  reactions_enabled: true
  misskey_compat_enabled: false
  landing_page: 'trends'
  wrapstodon: true
  mfm_enabled: false
  mfm_allow_composition: false
  force_mfm_enabled: false
  force_avatar_decorations: false
  force_round_avatar: false
  circles_enabled: false
  clips_enabled: false
  auto_quote_from_url: false
  avatar_decorations_enabled: false
  avatar_decorations_federation_enabled: false
  avatar_decorations_local_only_view: false
  avatar_decorations_max_count: 5
  allow_user_custom_css: false
  rate_limit_bypass_enabled: false
  board_announcements_enabled: true
  antenna_enabled: true
  online_status_enabled: false
  soft_hide_deletion: false

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
