defaults:
  site_title: 'Mastodon Custard Edition'
  theme_color: '#FFFD78'
  force_local_only: false
  local_account_statuses_access: 'public'
  local_status_page_access: 'public'
  visible_reactions: 6
  show_instance_info: true
  instance_metadata_enabled: true
  custom_emoji_size: false
  reaction_custom_emoji_size: false
  reaction_local_emoji_only: true
  reactions_enabled: true
  misskey_compat_enabled: false
  mfm_enabled: false
  mfm_allow_composition: false
  force_mfm_enabled: false
  force_avatar_decorations: false
  force_round_avatar: false
  circles_enabled: false
  clips_enabled: false
  auto_quote_from_url: false
  pages_enabled: false
  avatar_decorations_enabled: false
  avatar_decorations_federation_enabled: false
  avatar_decorations_local_only_view: false
  avatar_decorations_max_count: 5
  allow_user_custom_css: false
  rate_limit_bypass_enabled: false
  board_announcements_enabled: true
  antenna_enabled: true
  online_status_enabled: false
  soft_hide_deletion: false
  drive_enabled: false
  drive_quota: 500
  drive_max_file_size: 20
  drive_allowed_extensions: ''
